version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attendance_db
    ports:
      - "3308:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mysql_data:/var/lib/mysql
    networks:
      - technicalTestDexa
    restart: unless-stopped

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: technical-test-backend
    ports:
      - "5001:5000" # Express.js backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: attendance_db
    networks:
      - technicalTestDexa
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: technical-test-frontend
    ports:
      - "5175:5173" # React.js frontend
    depends_on:
      - backend
    networks:
      - technicalTestDexa
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  technicalTestDexa:
    # Specify driver options
    driver: bridge
