// Create a user 
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "mayer",
    "email": "mayer@mayer.com",
    "password": "password",
    "confPassword": "password",
    "gender": "Female",
    "role": "user"
}

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "johnDoe",
    "email": "johnDoe@johnDoe.com",
    "password": "password",
    "confPassword": "password",
    "gender": "Male",
    "role": "HRD"
}

### 
// Get all user
GET http://localhost:5000/users

###
// get single user1
GET http://localhost:5000/users/5fd52c5a-7b49-4836-ba3f-16a4dddf2f5f

###
// get single user2
GET http://localhost:5000/users/7d98c999-72dc-4d9e-bad3-c7bb06bfed43

###
// update user
PATCH http://localhost:5000/users/5fd52c5a-7b49-4836-ba3f-16a4dddf2f5f
Content-Type: application/json

{
    "name": "johnUpdated",
    "email": "john@mayer.com",
    "password": "",
    "confPassword": ""
}

###
// Login user admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "john@mayer.com",
    "password": "password"
}

###
// Login user non admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mayer@mayer.com",
    "password": "password"
}

### 
// Get current session
GET http://localhost:5000/me

###
// Logout user
DELETE http://localhost:5000/logout


###
// get all attendance
GET http://localhost:5000/attendances